version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      # jopt-simple is locked for Minecraft compatibility
      - dependency-name: "net.sf.jopt-simple:jopt-simple"